[package]
name = "mps-sys"
license = "MIT AND BSD-3-Clause" 
version = "0.1.0"
authors = ["Techcable <Techcable@techcable.net>"]
edition = "2018"
build = "build.rs"
# Unstable
publish = false

[dependencies]

[build-dependencies]
cc = "1"
bindgen = "0.58"

